### ISSUE TITLE
authentication error

### ISSUE THREAD

**Issue by ralphtheninja** [RichardLitt/ignore-github-users#4]
```
$ ignore-github-users greenkeeperio-bot                                                                                                       
{ [Error: {"message":"Requires authentication","documentation_url":"https://developer.github.com/v3"}]                                        
  status: 401,                                                                                                                                
  json:                                                                                                                                       
   { message: 'Requires authentication',                                                                                                      
     documentation_url: 'https://developer.github.com/v3' } }                                                                                 
TypeError: Cannot read property 'length' of undefined                                                                                         
    at /usr/local/lib/node_modules/ignore-github-users/cli.js:18:22                                                                           
    at tryCatcher (/usr/local/lib/node_modules/ignore-github-users/node_modules/bluebird/js/release/util.js:11:23)                            
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/ignore-github-users/node_modules/bluebird/js/release/promise.js:489:31) 
    at Promise._settlePromise (/usr/local/lib/node_modules/ignore-github-users/node_modules/bluebird/js/release/promise.js:546:18)            
    at Promise._settlePromise0 (/usr/local/lib/node_modules/ignore-github-users/node_modules/bluebird/js/release/promise.js:591:10)           
    at Promise._settlePromises (/usr/local/lib/node_modules/ignore-github-users/node_modules/bluebird/js/release/promise.js:674:18)           
    at Promise._fulfill (/usr/local/lib/node_modules/ignore-github-users/node_modules/bluebird/js/release/promise.js:615:18)                  
    at Promise._resolveCallback (/usr/local/lib/node_modules/ignore-github-users/node_modules/bluebird/js/release/promise.js:416:57)          
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/ignore-github-users/node_modules/bluebird/js/release/promise.js:502:17) 
    at Promise._settlePromise (/usr/local/lib/node_modules/ignore-github-users/node_modules/bluebird/js/release/promise.js:546:18)            
    at Promise._settlePromise0 (/usr/local/lib/node_modules/ignore-github-users/node_modules/bluebird/js/release/promise.js:591:10)           
    at Promise._settlePromises (/usr/local/lib/node_modules/ignore-github-users/node_modules/bluebird/js/release/promise.js:670:18)           
    at Promise._reject (/usr/local/lib/node_modules/ignore-github-users/node_modules/bluebird/js/release/promise.js:634:18)                   
    at Promise._settlePromise (/usr/local/lib/node_modules/ignore-github-users/node_modules/bluebird/js/release/promise.js:561:21)            
    at Promise._settlePromise0 (/usr/local/lib/node_modules/ignore-github-users/node_modules/bluebird/js/release/promise.js:591:10)           
    at Promise._settlePromises (/usr/local/lib/node_modules/ignore-github-users/node_modules/bluebird/js/release/promise.js:670:18)           
    at Promise._reject (/usr/local/lib/node_modules/ignore-github-users/node_modules/bluebird/js/release/promise.js:634:18)                   
    at Promise._rejectCallback (/usr/local/lib/node_modules/ignore-github-users/node_modules/bluebird/js/release/promise.js:452:10)           
    at ReductionPromiseArray.PromiseArray._reject (/usr/local/lib/node_modules/ignore-github-users/node_modules/bluebird/js/release/promise_ar
ray.js:136:19)                                                                                                                                
    at Promise._settlePromise (/usr/local/lib/node_modules/ignore-github-users/node_modules/bluebird/js/release/promise.js:543:21)            
    at Promise._settlePromise0 (/usr/local/lib/node_modules/ignore-github-users/node_modules/bluebird/js/release/promise.js:591:10)           
    at Promise._settlePromises (/usr/local/lib/node_modules/ignore-github-users/node_modules/bluebird/js/release/promise.js:670:18)           
    at Async._drainQueue (/usr/local/lib/node_modules/ignore-github-users/node_modules/bluebird/js/release/async.js:125:16)                   
    at Async._drainQueues (/usr/local/lib/node_modules/ignore-github-users/node_modules/bluebird/js/release/async.js:135:10)                  
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/ignore-github-users/node_modules/bluebird/js/release/async.j
s:16:14)                                                                                                                                      
    at processImmediate [as _immediateCallback] (timers.js:383:17)                                                                            
```

**Comment by RichardLitt** [comment]
Working on this. Opened https://github.com/rvagg/ghauth/issues/18 to address current blocker.

**Comment by RichardLitt** [comment]
Reinstall and try now. Works for me.

**Comment by ralphtheninja** [comment]
:white_check_mark:
